title: Susan D. Hyde
description: Professor of Political Science, University of California, Berkeley
theme: minima
baseurl: ""
url: "https://hydesusan.github.io"

header_pages:
  - index.md
  - research.md
  - cv.md
  - teaching.md
  - phd-students.md
  - contact.md
  - links.md
  - letters.md
